### PR TITLE
Various Improvements

### PR DESCRIPTION
**Pull request by Rahix**
Hi, so these are some changes I did while starting to dive deeper into the crate.  No functional changes so far, just structural ones.  I have some ideas for functional changes but I wanted to get these other things out of the way first.

I know this is quite a large changeset and I understand if you don't like some of the changes I did.  I tried keeping each change in a separate commit, so you'll have an easier time reviewing this PR by going through it commit by commit.  If you don't like something, I can drop the related commit again.

Importantly, there are **breaking changes** in here.  I would suggest to not release them right away as I want to send you some more PRs with functional changes that are also API breaking...  Although I cannot promise a timeframe for that, so you'll have to decide how you want to proceed...

Now, to give a rough overview (for the details, look at the individual commit messages):

- I've made the crate-features purely additive as that's how cargo features are meant to be used [^1].
- I've shuffled some items in the crate around to (in my eyes) clean-up the crate structure a bit.
- I've adjusted the GitHub Actions workflow again for the changes and to fix some things I missed last time around.
- And finally I've updated the README to reflect the changes and to fix some issues in it ([README preview](https://github.com/Rahix/rmodbus/blob/changes/README.md)).  I've also moved the changelog into its own file so it is easier to find.

Please let me know what you think of this!

[^1]: https://doc.rust-lang.org/cargo/reference/features.html#feature-unification

### CODE REVIEW

**Comment by divi255** [comment]
Thanks for the huge work. I am going to review all the commits next week. As there are lots, it could take some time.

**Comment by Rahix** [comment]
Don't worry, take your time.

**Comment by divi255** [comment]
Modbus context size is a disputable thing. I agree to make small as the default one (with increasing crate minor ver) but "full context" is not clear. I'm going to merge that commit but I'll add two features instead to set the size: modicon (the classic one, with 10k registers per type) and full (65535, max allowed currently)

**Comment by Rahix** [comment]
> I agree to make small as the default one

Careful, right now the "full" (10k) context is still the default because the `fullcontext` feature is enabled by default.  I only did this change so the feature complies with the "additive only" design.

**Comment by divi255** [comment]
Ah, ok. That's fine then let's keep it as-is

**Pull request merged**
