### PR TITLE
make ModbusContext a trait and move it sample impl to ModbusStorage

### PR DESCRIPTION
**Pull request by dragonnn**
This should fix https://github.com/alttch/rmodbus/issues/23
I need it to myself.
It is a breaking change but allows the usage of rmodbus like before by just changing a few imports.
Maybe they could be a simple way to define a trait  then just coping everything `ModbusContext` had before it but I think to begin with this is still worth having.
Bumped the version to already in this PR.

### CODE REVIEW

**Comment by bart-sensirion-qm** [comment]
I don't think it's necessary to extract the context to a trait and have a breaking change to enable external handling of reads and writes. Please take a look at my PR #25, see if it's sufficient for your needs and provide any feedback you have. Also feel free to join the conversation in #23 to have a wider discussion on ways to approach the issue.

**Comment by divi255** [comment]
sorry for the delay, your pr is in my TODO

**Comment by divi255** [comment]
merged but going to be released later after I check all the compatibility with previous versions

**Comment by divi255** [comment]
the commit breaks no-std support. I'll try to resolve it later or better please try doing it by yourself.

**Comment by dragonnn** [comment]
Hmmm that is strange, since I do use it on no-std from my branch? What exactly does it break?
I will have time to investigate it a bit more on Monday

**Comment by divi255** [comment]
cargo test --no-default-features -- --test-threads=1 --nocapture

it fails because src/server/mod.rs now depends on std::slice

**Comment by divi255** [comment]
ah sorry it was another pull req. your seems to be fine, nevermind

**Pull request merged**
