### PR TITLE
Add extern read/write handling (not needing ModbusContext)

### LINKED ISSUE #23: Discuss custom modbus context
I'm currently trying to use rmodbus at work and am running into some trouble. Where I'm integrating the library the data behind the registers is spread throughout the rest of the code. The library however is written with the assumption that the information will be stored in a ModbusContext. If anything else in the program wants to use this data there are three main choices I can see
1) Keep the ModbusContext as the place where the data is stored, other parts of the program will have to go through the context to read/write it.
2) Keep the data wherever it resides and map the calls from rmodbus to this data.
3) Duplicate the data and try to keep the two copies in sync.

Currently only option 1 is supported (as far as I can see looking at the library) but I think it's self evident that option 2 is preferabele in some cases. I'd like to discuss whether the maintainers would be open to support this usecase and how to best implement this. I would of course help with the work or just send in a PR with the functionality if we can agree on how to implement this.

### PR DESCRIPTION
**Pull request by bart-sensirion-qm**
I've implemented the discussed changes (#23) on my fork, please take a look. Please note that the API is only extended in this PR which means there are no breaking changes. Documentation and testing isn't done yet but I've used the changes in an internal codebase to give it a testdrive and they seem ergonomic enough to me. If this seems acceptable I was thinking to try to extend the tests and add an example to the documentation before this is merged.
fixes #23

### CODE REVIEW

**Comment by bart-sensirion-qm** [comment]
I only now noticed I forgot to bump the version number :(

**Comment by divi255** [comment]
sorry for the delay, your pr is in my TODO

**Comment by divi255** [comment]
merged but going to be released later after I check all the compatibility with previous versions

**Comment by divi255** [comment]
cargo test --no-default-features -- --test-threads=1 --nocapture

it fails because src/server/mod.rs now depends on std::slice

please check the compatibility with nostd

**Comment by bart-sensirion-qm** [comment]
Hey, thanks for the merge and your reactions, the failing test is because I forgot to commit a one line fix (`core::slice` import instead of `std::slice`). I was also planning to add some extra documentation and tests for the new feature after discussing my PR but I'll open a new PR for those things and the fix as this one merged already.

**Pull request merged**
